---
# API version and kind of the resource
apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential

# Metadata for the resource
metadata:
  name: docker-cluster-cred  # Name of the credential resource

# Specification of the credential
spec:
  identityRef:  # Reference to the identity secret
    apiVersion: v1  # API version of the secret
    kind: Secret  # Kind of the referenced resource
    name: docker-cluster-secret  # Name of the secret
    namespace: kcm-system  # Namespace of the secret
