---
# Namespace for the resources defined in this kustomization
namespace: kcm-system

# Metadata to include in the generated resources
buildMetadata:
  - managedByLabel  # Adds a label indicating the manager of the resource
  - originAnnotations  # Adds annotations indicating the origin of the resource

# Options for the generator
# Disables the addition of a hash suffix to resource names
# This ensures predictable resource names
generatorOptions:
  disableNameSuffixHash: true

# List of resources to include in this kustomization
resources:
  - cluster  # Cluster-level resources
  - service  # Service-level resources
  - source   # Source-level resources
  - addon.yaml  # Add-on configurations
  - core.yaml   # Core configurations
  - crd.yaml    # Custom Resource Definitions
