---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
spec:
  interval: 10m
  releaseName: cni
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/cilium
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - # docker.io/library/busybox:1.37.0
            name: docker.io/library/busybox
            digest: sha256:498a000f370d8c37927118ed80afe8adc38d1edcbfc071627d17b25c88efcab0
          - # ghcr.io/spiffe/spire-server:1.11.2
            name: ghcr.io/spiffe/spire-server
            digest: sha256:0ca091ecef5cbc19f2900a789f68ff5c00a31b056768468c6f2d4c3160a7f03c
          - # quay.io/cilium/certgen:v0.1.17
            name: quay.io/cilium/certgen
            digest: sha256:6c114865c59148199416316901eb7b48ba0d9e04df43da8759ce5bc5571ba95b
          - # quay.io/cilium/cilium:v1.17.2
            name: quay.io/cilium/cilium
            digest: sha256:3c4c9932b5d8368619cb922a497ff2ebc8def5f41c18e410bcc84025fcd385b1
          - # quay.io/cilium/cilium-envoy:v1.32.3-1742121615-a3c9b397476153e650055c63cd73cc195b1216f0
            name: quay.io/cilium/cilium-envoy
            digest: sha256:9faf5b3cfde932a917c04aa95a07b58a399247debd5c06d05e11f74c03655c3f
          - # quay.io/cilium/clustermesh-apiserver:v1.17.2
            name: quay.io/cilium/clustermesh-apiserver
            digest: sha256:981250ebdc6e66e190992eaf75cfca169113a8f08d5c3793fe15822176980398
          - # quay.io/cilium/hubble-relay:v1.17.2
            name: quay.io/cilium/hubble-relay
            digest: sha256:42a8db5c256c516cacb5b8937c321b2373ad7a6b0a1e5a5120d5028433d586cc
          - # quay.io/cilium/operator:v1.17.2
            name: quay.io/cilium/operator
            digest: sha256:697a7e6c4765ef053d33dd2d9d7f14642c01dfa7333ad7902de7ca5afbf3b419
  values:
    kubeProxyReplacement: true
    bgpControlPlane:
      enabled: true
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
    envoy:
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_ADMIN
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    hubble:
      metrics:
        serviceMonitor:
          enabled: true
      relay:
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
    monitor:
      enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
