---
# Namespace for the resources defined in this kustomization
namespace: kcm-system

# Metadata to include in the generated resources
buildMetadata:
  - managedByLabel  # Adds a label indicating the manager of the resource
  - originAnnotations  # Adds annotations indicating the origin of the resource

# Options for the generator
# Disables the addition of a hash suffix to resource names
# This ensures predictable resource names
generatorOptions:
  disableNameSuffixHash: true
  labels:
    k0rdent.mirantis.com/component: kcm  # Label indicating the component
  annotations:
    projectsveltos.io/template: "true"  # Annotation indicating a template

# Secret generator configuration
secretGenerator:
  - name: vsphere-cluster-secret  # Name of the generated secret

# List of resources to include in this kustomization
resources:
  - credential.yaml  # Credential configuration for vSphere
  - vsphere-standalone-cp.yaml  # vSphere standalone control plane configuration
