---
kind: Component
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      owner: kubernetes
      component: codecloud
resources:
  - ../../resource/cicd/gitea
  - ../../resource/cicd/sonarqube
