---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 10m
  releaseName: tempo
  timeout: 5m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.32.7
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - # docker.io/bitnami/kubectl:1.32.3
            name: docker.io/bitnami/kubectl
            digest: sha256:3f21647d4c3f0fa0a906d6aacf7919beac2356bf6a2fb595414bea045ba75270
          - # docker.io/grafana/enterprise-traces:v2.7.0
            name: docker.io/grafana/enterprise-traces
            digest: sha256:08189fcaac7f2cc29bc44e05e439f0475b105b013403142ea0d5bd1ab1c61f89
          - # docker.io/grafana/tempo:2.7.1
            name: docker.io/grafana/tempo
            digest: sha256:4443be217c396b065ee34845534199c36fdba4dc619cb96550e228d73fba6e69
          - # docker.io/grafana/tempo-query:2.7.1
            name: docker.io/grafana/tempo-query
            digest: sha256:e92491e0319d84feaa716d21650ea4410712236017dd7f1375559974100bb14d
          - # docker.io/grafanalabs-global/docker-enterprise-provisioner-prod/enterprise-provisioner
            name: docker.io/grafanalabs-global/docker-enterprise-provisioner-prod/enterprise-provisioner
          - # docker.io/memcached:1.6.37
            name: docker.io/memcached
            digest: sha256:f23cef7900b19773bcee717842541b10527456fe464bc2b8a84e49bc01fff9b4
          - # docker.io/nginxinc/nginx-unprivileged:1.27.4-alpine
            name: docker.io/nginxinc/nginx-unprivileged
            digest: sha256:73ee3356fe50559ece217d0fefcff35cdece6a67a49c1583433ea7cb6b7445aa
          - # docker.io/prom/memcached-exporter:v0.15.1
            name: docker.io/prom/memcached-exporter
            digest: sha256:bc441feeb97304c7af70c76ee465080c9e071665560bfbd31cd24318c202ed18
  values:
    ingester:
      replicas: 3
      persistence:
        enabled: false
    metricsGenerator:
      enabled: true
      replicas: 1
      persistence:
        enabled: false
      config:
        processor:
          local_blocks:
            filter_server_spans: false
            flush_to_storage: true
    distributor:
      replicas: 1
    compactor:
      replicas: 1
    querier:
      replicas: 1
    queryFrontend:
      query:
        enabled: false
      replicas: 1
    enterpriseFederationFrontend:
      enabled: false
      replicas: 1
    multitenancyEnabled: false
    rollout_operator:
      enabled: false
    traces:
      jaeger:
        grpc:
          enabled: false
        thriftBinary:
          enabled: false
        thriftCompact:
          enabled: false
        thriftHttp:
          enabled: false
      zipkin:
        enabled: false
      otlp:
        http:
          enabled: false
        grpc:
          enabled: false
      opencensus:
        enabled: false
        receiverConfig: {}
    cache:
      caches:
        - memcached:
            host: '{{ include "tempo.fullname" . }}-memcached'
            service: memcached-client
            consistent_hash: true
            timeout: 500ms
          roles:
            - parquet-footer
            - bloom
            - frontend-search
    storage:
      trace:
        backend: local
      admin:
        backend: filesystem
    memcached:
      enabled: true
      image:
      replicas: 1
    memcachedExporter:
      enabled: false
    metaMonitoring:
      serviceMonitor:
        enabled: true
        metrics:
          remote:
            url: ""
            auth:
              username: ""
              passwordSecretName: ""
              passwordSecretKey: ""
          scrapeK8s:
            enabled: true
    prometheusRule:
      enabled: true
      groups:
        - name: loki-rules
          rules:
            - record: job:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
            - record: job_route:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
            - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
              expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)
    minio:
      enabled: false
    gateway:
      enabled: false
      replicas: 1
      basicAuth:
        enabled: false
        existingSecret: null
    enterprise:
      enabled: false
    license:
      contents: NOTAVALIDLICENSE
      external: false
      secretName: '{{ include "tempo.resourceName" (dict "ctx" . "component" "license") }}'
    provisioner:
      enabled: false
      apiUrl: ""
    adminApi:
      replicas: 1
    enterpriseGateway:
      useDefaultProxyURLs: true
      replicas: 1
