---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-eventing
spec:
  interval: 10m
  releaseName: knative-eventing
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/knative-eventing
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  dependsOn:
    - name: knative-serving
    - name: knative-operator
      namespace: operators
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images: []
  values:
    knative:
      defaultBrokerClass: MTChannelBasedBroker
    config:
      broker:
        enabled: true
        spec:
          config:
            default-br-config: |
              clusterDefault:
                apiVersion: v1
                kind: ConfigMap
                name: config-br-default-channel
                namespace: knative
                brokerClass: MTChannelBasedBroker
                delivery:
                  backoffDelay: PT0.2S
                  backoffPolicy: exponential
                  retry: 10
    sources:
      ceph:
        enabled: false
      github:
        enabled: true
      rabbitmq:
        enabled: false
      redis:
        enabled: false
    backstage:
      enabled: false
