---
kind: Kustomization
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../resource/core/cni
  - ../../../resource/core/cni/resource
patches:
  - path: cni.yaml
