---
# API version and kind of the resource
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService

# Metadata for the resource
metadata:
  name: mgmt-mcs  # Name of the multi-cluster service resource

# Specification of the multi-cluster service
spec:
  clusterSelector:  # Selector to identify target clusters
    matchLabels:
      k0rdent.mirantis.com/management-cluster: "true"  # Label indicating a management cluster
      sveltos-agent: present  # Label indicating the presence of a Sveltos agent
  serviceSpec:  # Specification of the services
    priority: 100  # Priority of the service
    services:
      - template: external-snapshotter-crd  # Template for the service
        name: external-snapshotter-crd  # Name of the service
        namespace: kube-system  # Namespace of the service
      - template: gateway-api-experimental-crd  # Template for the service
        name: gateway-api-experimental-crd  # Name of the service
        namespace: kube-system  # Namespace of the service
      # - template: edns-1-0-0
      #   name: edns
      #   namespace: kube-system
      #   values: ""
      - template: gateway-1-0-0
        name: gateway
        namespace: kube-system
        values: |
          gateways:
            - name: default-gateway
              className: cilium
              listeners:
                - name: http
                  port: 80
                  protocol: HTTP
                  allowedRoutes:
                    namespaces:
                      from: All
                - name: https
                  port: 443
                  protocol: HTTPS
                  hostname: "*.local"
                  allowedRoutes:
                    namespaces:
                      from: All
                  tls:
                    mode: Terminate
                    certificateRefs:
                      - name: default-gw-cert
                        issuer: self-signed-ca-issuer
            - name: tls-gateway
              className: cilium
              listeners:
                - name: tls
                  port: 443
                  protocol: TLS
                  allowedRoutes:
                    namespaces:
                      from: All
                    kinds:
                      - kind: TLSRoute
                  tls:
                    mode: Passthrough
