---
namespace: ucp
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      owner: kubernetes
      addon: ucp
resources:
  - release.yaml
