---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  values:
    ingester:
      replicas: 1
    config: |
      multitenancy_enabled: {{ .Values.multitenancyEnabled }}

      usage_report:
        reporting_enabled: {{ .Values.reportingEnabled }}

      {{- if .Values.enterprise.enabled }}
      license:
        path: "/license/license.jwt"

      admin_api:
        leader_election:
          enabled: true
          ring:
            kvstore:
              store: "memberlist"

      auth:
        type: enterprise

      http_api_prefix: {{get .Values.tempo.structuredConfig "http_api_prefix"}}

      admin_client:
        storage:
          backend: {{.Values.storage.admin.backend}}
          {{- if eq .Values.storage.admin.backend "s3"}}
          s3:
            {{- toYaml .Values.storage.admin.s3 | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.admin.backend "gcs"}}
          gcs:
            {{- toYaml .Values.storage.admin.gcs | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.admin.backend "azure"}}
          azure:
            {{- toYaml .Values.storage.admin.azure | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.admin.backend "swift"}}
          swift:
            {{- toYaml .Values.storage.admin.swift | nindent 6}}
          {{- end}}
          {{- if eq .Values.storage.admin.backend "filesystem"}}
          filesystem:
            {{- toYaml .Values.storage.admin.filesystem | nindent 6}}
          {{- end}}
      {{- end }}

      {{- if and .Values.enterprise.enabled .Values.enterpriseGateway.useDefaultProxyURLs }}
      gateway:
        proxy:
          admin_api:
            url: http://{{ template "tempo.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
          compactor:
            url: http://{{ template "tempo.fullname" . }}-compactor.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
          default:
            url: http://{{ template "tempo.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
          distributor:
            url: http://{{ template "tempo.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
            otlp/grpc:
              url: h2c://{{ template "tempo.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:4317
            otlp/http:
              url: http://{{ template "tempo.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:4318
          ingester:
            url: http://{{ template "tempo.fullname" . }}-ingester.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
          querier:
            url: http://{{ template "tempo.fullname" . }}-querier.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}
          query_frontend:
            url: http://{{ template "tempo.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:{{ include "tempo.serverHttpListenPort" . }}{{get .Values.tempo.structuredConfig "http_api_prefix"}}
      {{else}}
      {{- if and .Values.enterprise.enabled .Values.enterpriseGateway.proxy }}
      gateway:
        proxy: {{- toYaml .Values.enterpriseGateway.proxy | nindent 6 }}
      {{- end }}
      {{- end }}

      compactor:
        compaction:
          block_retention: {{ .Values.compactor.config.compaction.block_retention }}
          compacted_block_retention: {{ .Values.compactor.config.compaction.compacted_block_retention }}
          compaction_window: {{ .Values.compactor.config.compaction.compaction_window }}
          v2_in_buffer_bytes: {{ .Values.compactor.config.compaction.v2_in_buffer_bytes }}
          v2_out_buffer_bytes: {{ .Values.compactor.config.compaction.v2_out_buffer_bytes }}
          max_compaction_objects: {{ .Values.compactor.config.compaction.max_compaction_objects }}
          max_block_bytes: {{ .Values.compactor.config.compaction.max_block_bytes }}
          retention_concurrency: {{ .Values.compactor.config.compaction.retention_concurrency }}
          v2_prefetch_traces_count: {{ .Values.compactor.config.compaction.v2_prefetch_traces_count }}
          max_time_per_tenant: {{ .Values.compactor.config.compaction.max_time_per_tenant }}
          compaction_cycle: {{ .Values.compactor.config.compaction.compaction_cycle }}
        ring:
          kvstore:
            store: memberlist
      {{- if and .Values.enterprise.enabled .Values.enterpriseFederationFrontend.enabled }}
      federation:
        proxy_targets:
          {{- toYaml .Values.enterpriseFederationFrontend.proxy_targets | nindent 6 }}
      {{- end }}
      {{- if .Values.metricsGenerator.enabled }}
      metrics_generator:
        ring:
          kvstore:
            store: memberlist
        processor:
          {{- toYaml .Values.metricsGenerator.config.processor | nindent 6 }}
        storage:
          {{- toYaml .Values.metricsGenerator.config.storage | nindent 6 }}
        traces_storage:
          {{- toYaml .Values.metricsGenerator.config.traces_storage | nindent 6 }}
        registry:
          {{- toYaml .Values.metricsGenerator.config.registry | nindent 6 }}
        metrics_ingestion_time_range_slack: {{ .Values.metricsGenerator.config.metrics_ingestion_time_range_slack }}
      {{- end }}
      distributor:
        ring:
          kvstore:
            store: memberlist
        receivers:
          {{- if  or (.Values.traces.jaeger.thriftCompact.enabled) (.Values.traces.jaeger.thriftBinary.enabled) (.Values.traces.jaeger.thriftHttp.enabled) (.Values.traces.jaeger.grpc.enabled) }}
          jaeger:
            protocols:
              {{- if .Values.traces.jaeger.thriftCompact.enabled }}
              thrift_compact:
                {{- $mergedJaegerThriftCompactConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:6831") .Values.traces.jaeger.thriftCompact.receiverConfig }}
                {{- toYaml $mergedJaegerThriftCompactConfig | nindent 10 }}
              {{- end }}
              {{- if .Values.traces.jaeger.thriftBinary.enabled }}
              thrift_binary:
                {{- $mergedJaegerThriftBinaryConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:6832") .Values.traces.jaeger.thriftBinary.receiverConfig }}
                {{- toYaml $mergedJaegerThriftBinaryConfig | nindent 10 }}
              {{- end }}
              {{- if .Values.traces.jaeger.thriftHttp.enabled }}
              thrift_http:
                {{- $mergedJaegerThriftHttpConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:14268") .Values.traces.jaeger.thriftHttp.receiverConfig }}
                {{- toYaml $mergedJaegerThriftHttpConfig | nindent 10 }}
              {{- end }}
              {{- if .Values.traces.jaeger.grpc.enabled }}
              grpc:
                {{- $mergedJaegerGrpcConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:14250") .Values.traces.jaeger.grpc.receiverConfig }}
                {{- toYaml $mergedJaegerGrpcConfig | nindent 10 }}
              {{- end }}
          {{- end }}
          {{- if .Values.traces.zipkin.enabled }}
          zipkin:
            {{- $mergedZipkinReceiverConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:9411") .Values.traces.zipkin.receiverConfig }}
            {{- toYaml $mergedZipkinReceiverConfig | nindent 6 }}
          {{- end }}
          {{- if or (.Values.traces.otlp.http.enabled) (.Values.traces.otlp.grpc.enabled) }}
          otlp:
            protocols:
              {{- if .Values.traces.otlp.http.enabled }}
              http:
                {{- $mergedOtlpHttpReceiverConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:4318") .Values.traces.otlp.http.receiverConfig }}
                {{- toYaml $mergedOtlpHttpReceiverConfig | nindent 10 }}
              {{- end }}
              {{- if .Values.traces.otlp.grpc.enabled }}
              grpc:
                {{- $mergedOtlpGrpcReceiverConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:4317") .Values.traces.otlp.grpc.receiverConfig }}
                {{- toYaml $mergedOtlpGrpcReceiverConfig | nindent 10 }}
              {{- end }}
          {{- end }}
          {{- if .Values.traces.opencensus.enabled }}
          opencensus:
            {{- $mergedOpencensusReceiverConfig := mustMergeOverwrite (dict "endpoint" "0.0.0.0:55678") .Values.traces.opencensus.receiverConfig }}
            {{- toYaml $mergedOpencensusReceiverConfig | nindent 6 }}
          {{- end }}
          {{- if .Values.traces.kafka }}
          kafka:
            {{- toYaml .Values.traces.kafka | nindent 6 }}
          {{- end }}
        {{- if .Values.distributor.config.log_discarded_spans.enabled }}
        log_discarded_spans:
          enabled: {{ .Values.distributor.config.log_discarded_spans.enabled }}
          include_all_attributes: {{ .Values.distributor.config.log_discarded_spans.include_all_attributes }}
          filter_by_status_error: {{ .Values.distributor.config.log_discarded_spans.filter_by_status_error }}
        {{- end }}
        {{- if or .Values.distributor.config.log_received_traces .Values.distributor.config.log_received_spans.enabled }}
        log_received_spans:
          enabled: {{ or .Values.distributor.config.log_received_traces .Values.distributor.config.log_received_spans.enabled }}
          include_all_attributes: {{ .Values.distributor.config.log_received_spans.include_all_attributes }}
          filter_by_status_error: {{ .Values.distributor.config.log_received_spans.filter_by_status_error }}
        {{- end }}
        {{- if .Values.distributor.config.extend_writes }}
        extend_writes: {{ .Values.distributor.config.extend_writes }}
        {{- end }}
      querier:
        frontend_worker:
          frontend_address: {{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend-discovery") }}:9095
          {{- if .Values.querier.config.frontend_worker.grpc_client_config }}
          grpc_client_config:
            {{- toYaml .Values.querier.config.frontend_worker.grpc_client_config | nindent 6 }}
          {{- end }}
        trace_by_id:
          query_timeout: {{ .Values.querier.config.trace_by_id.query_timeout }}
        search:
          query_timeout: {{ .Values.querier.config.search.query_timeout }}
        max_concurrent_queries: {{ .Values.querier.config.max_concurrent_queries }}
      query_frontend:
        max_outstanding_per_tenant: {{ .Values.queryFrontend.config.max_outstanding_per_tenant }}
        max_retries: {{ .Values.queryFrontend.config.max_retries }}
        search:
          target_bytes_per_job: {{ .Values.queryFrontend.config.search.target_bytes_per_job }}
          concurrent_jobs: {{ .Values.queryFrontend.config.search.concurrent_jobs }}
        trace_by_id:
          query_shards: {{ .Values.queryFrontend.config.trace_by_id.query_shards }}
        metrics:
          concurrent_jobs:  {{ .Values.queryFrontend.config.metrics.concurrent_jobs }}
          target_bytes_per_job:  {{ .Values.queryFrontend.config.metrics.target_bytes_per_job }}
          max_duration: {{ .Values.queryFrontend.config.metrics.max_duration }}
          query_backend_after: {{ .Values.queryFrontend.config.metrics.query_backend_after }}
          interval: {{ .Values.queryFrontend.config.metrics.interval }}
          duration_slo: {{ .Values.queryFrontend.config.metrics.duration_slo }}
          throughput_bytes_slo: {{ .Values.queryFrontend.config.metrics.throughput_bytes_slo }}
      ingester:
        lifecycler:
          ring:
            replication_factor: {{ .Values.ingester.config.replication_factor }}
            {{- if .Values.ingester.zoneAwareReplication.enabled }}
            zone_awareness_enabled: true
            {{- end }}
            kvstore:
              store: memberlist
          tokens_file_path: /var/tempo/tokens.json
        {{- if .Values.ingester.config.trace_idle_period }}
        trace_idle_period: {{ .Values.ingester.config.trace_idle_period }}
        {{- end }}
        {{- if .Values.ingester.config.flush_check_period }}
        flush_check_period: {{ .Values.ingester.config.flush_check_period }}
        {{- end }}
        {{- if .Values.ingester.config.max_block_bytes }}
        max_block_bytes: {{ .Values.ingester.config.max_block_bytes }}
        {{- end }}
        {{- if .Values.ingester.config.max_block_duration }}
        max_block_duration: {{ .Values.ingester.config.max_block_duration }}
        {{- end }}
        {{- if .Values.ingester.config.complete_block_timeout }}
        complete_block_timeout: {{ .Values.ingester.config.complete_block_timeout }}
        {{- end }}
        {{- if .Values.ingester.config.flush_all_on_shutdown }}
        flush_all_on_shutdown: {{ .Values.ingester.config.flush_all_on_shutdown }}
        {{- end }}
      memberlist:
        {{- with .Values.memberlist }}
          {{- toYaml . | nindent 2 }}
        {{- end }}
        join_members:
          - dns+{{ include "tempo.fullname" . }}-gossip-ring:{{ .Values.memberlist.bind_port }}
      overrides:
        {{- toYaml .Values.global_overrides | nindent 2 }}
      server:
        http_listen_port: {{ .Values.server.httpListenPort }}
        log_level: {{ .Values.server.logLevel }}
        log_format: {{ .Values.server.logFormat }}
        grpc_server_max_recv_msg_size: {{ .Values.server.grpc_server_max_recv_msg_size }}
        grpc_server_max_send_msg_size: {{ .Values.server.grpc_server_max_send_msg_size }}
        http_server_read_timeout: {{ .Values.server.http_server_read_timeout }}
        http_server_write_timeout: {{ .Values.server.http_server_write_timeout }}
      cache:
      {{- toYaml .Values.cache | nindent 2}}
      storage:
        trace:
          {{- if .Values.storage.trace.block.version }}
          block:
            version: {{.Values.storage.trace.block.version}}
            {{- if .Values.storage.trace.block.dedicated_columns}}
            parquet_dedicated_columns:
              {{ .Values.storage.trace.block.dedicated_columns | toYaml | nindent 8}}
            {{- end }}
          {{- end }}
          pool:
            max_workers: {{ .Values.storage.trace.pool.max_workers }}
            queue_depth: {{ .Values.storage.trace.pool.queue_depth }}
          backend: {{.Values.storage.trace.backend}}
          {{- if eq .Values.storage.trace.backend "s3"}}
          s3:
            {{- toYaml .Values.storage.trace.s3 | nindent 6}}
          {{- end }}
          {{- if eq .Values.storage.trace.backend "gcs"}}
          gcs:
            {{- toYaml .Values.storage.trace.gcs | nindent 6}}
          {{- end }}
          {{- if eq .Values.storage.trace.backend "azure"}}
          azure:
            {{- toYaml .Values.storage.trace.azure | nindent 6}}
          {{- end }}
          blocklist_poll: 5m
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
