---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: github
spec:
  interval: 5m0s
  type: oci
  url: oci://ghcr.io
# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: grafana
# spec:
#   interval: 5m0s
#   url: https://grafana.github.io/helm-charts
