---
kind: Component
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../resource/core/knative
  - ../../../resource/core/knative/eventing
  - ../../../resource/core/knative/serving
  - gateway.yaml
patches:
  - path: server.yaml
