---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni-resource
spec:
  interval: 10m
  releaseName: cni-resource
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/cni-resource
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  dependsOn:
    - name: cni
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images: []
  values:
    cilium:
      pool:
        enabled: true
        allowFirstLastIPs: No
      advert:
        l2:
          enabled: false
        bgp:
          enabled: true
          service:
            addresses:
              - ExternalIP
              - LoadBalancerIP
      config:
        cluster:
          enabled: true
        peer:
          enabled: true
          authSecretRef: bgp
          gracefulRestart: true
          holdTimeSec: 9
          keepAliveTimeSec: 3
          multiHop: 4
          restartTimeSec: 15
          addressFamilies:
            - afi: ipv4
              safi: unicast
              advertisements:
                matchLabels:
                  advertise: bgp
