---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi
spec:
  interval: 10m
  releaseName: csi
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - # docker.io/bitnami/kubectl:1.32.3
            name: docker.io/bitnami/kubectl
            digest: sha256:3f21647d4c3f0fa0a906d6aacf7919beac2356bf6a2fb595414bea045ba75270
          - # docker.io/openebs/admission-server:2.12.2
            name: docker.io/openebs/admission-server
            digest: sha256:bfe2f71f2c5d041b880edd1ade5a0f2950332a00097c2485824ffa97c820d968
          - # docker.io/openebs/linux-utils:4.1.0
            name: docker.io/openebs/linux-utils
            digest: sha256:f085850f69fdb278416d353a1bc1174613251ca9c471f5acd0e627eeb43e5d9e
          - # docker.io/openebs/m-apiserver:2.12.2
            name: docker.io/openebs/m-apiserver
            digest: sha256:1fbfe26ef88d7bb0849c883129d5e3379ccbb624ca13cd2b0197d8f1b0d7a560
          - # docker.io/openebs/m-exporter:3.6.0
            name: docker.io/openebs/m-exporter
            digest: sha256:fe7563a85139151a1b4834e371234574d71319f2f2bbbd1e7b558989cd84f19a
          - # docker.io/openebs/openebs-k8s-provisioner:2.12.2
            name: docker.io/openebs/openebs-k8s-provisioner
            digest: sha256:7ecda3ffb4f7be48fb301469d3cf143281ae3943a9ee8ad04d385f79bd51913f
          - # docker.io/openebs/provisioner-localpv:4.2.0
            name: docker.io/openebs/provisioner-localpv
            digest: sha256:23f8e4cae8c7e3aefc28d95338a355cde7a943b96005b5b62a7f58491413c1ed
          - # docker.io/openebs/snapshot-controller:2.12.2
            name: docker.io/openebs/snapshot-controller
            digest: sha256:ea8296953f58beba0ce880b449ca07e818d318010b441e95d713797efb1a6668
          - # docker.io/openebs/snapshot-provisioner:2.12.2
            name: docker.io/openebs/snapshot-provisioner
            digest: sha256:90920d9ed40ae68d213c6842a1ce277716be238f36cbfaf8002a5cd38cd1f960
  values:
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    zfs-localpv:
      crds:
        zfsLocalPv:
          enabled: true
        csi:
          volumeSnapshots:
            enabled: true
    lvm-localpv:
      crds:
        lvmLocalPv:
          enabled: false
        csi:
          volumeSnapshots:
            enabled: true
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      analytics:
        enabled: false
      hostpathClass:
        enabled: true
        isDefaultClass: true
        name: general
      localpv:
        enabled: true
