---
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - certmanager
  - gateway
  - gatekeeper.yaml
  - metrics.yaml
  - namespace.yaml
