---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics
  namespace: kube-system
spec:
  interval: 10m
  releaseName: metrics
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/metrics-server
      version: 7.4.2
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - # docker.io/bitnami/metrics-server:0.7.2
            name: docker.io/bitnami/metrics-server
            digest: sha256:46f586f53d7eb8ae3e13381e427d94187fac0b58f1f42b929523104f92c419b4
  values:
    apiService:
      create: true
    resourcesPreset: none
    # fixme: enable readiness probe
    readinessProbe:
      enabled: false
