---
kind: Component
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../crd
  - ../resource/core
  - ../resource/addon/cicd
  # - ../resource/addon/sre
  # - ../resource/addon/ucp
patches:
  # - path: clusterissuer.yaml
  - patch: |
      - op: add
        path: /spec/values/global
        value:
          storageClass: general
    target:
      kind: HelmRelease
      name: flux
