---
# API version and kind of the resource
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment

# Metadata for the resource
metadata:
  name: dev-openstack  # Name of the cluster deployment
  namespace: default  # Namespace for the deployment

# Specification of the cluster deployment
spec:
  template: openstack-cluster-0-0-1  # Template for the cluster
  credential: openstack-cluster-cred  # Credential for the cluster
  propagateCredentials: false  # Whether to propagate credentials
  config:
    clusterLabels: {} # Labels for the cluster
    k0s:
      api:
        sans:
          - openstack.kubernetes.local  # Subject Alternative Names for the API server
      network:
        provider: custom  # Network provider
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
