---
# API version and kind of the resource
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment

# Metadata for the resource
metadata:
  name: dev-docker  # Name of the cluster deployment
  namespace: default  # Namespace for the deployment

# Specification of the cluster deployment
spec:
  dryRun: false  # Indicates whether the deployment is a dry run
  template: docker-hosted-cp-1-0-0  # Template for the cluster
  credential: docker-cluster-cred  # Credential for the cluster
  propagateCredentials: false  # Whether to propagate credentials
  config:
    clusterLabels: {} # Labels for the cluster
    k0s:
      api:
        sans:
          - docker.kubernetes.local  # Subject Alternative Names for the API server
      network:
        provider: custom  # Network provider
      featureGates:
        - name: UserNamespacesSupport
          enabled: true
