---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-serving
spec:
  interval: 10m
  releaseName: knative-serving
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/knative-serving
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  dependsOn:
    - name: knative-operator
      namespace: operators
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images: []
  values:
    knative:
      security:
        enabled: false
        guard: false
      network:
        gatewayAPI:
          enabled: true
      ingress:
        type: gateway-api
    ca-issuer:
      enabled: true
