---
apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: k0s-addon-chart-k8s-monitoring
  namespace: kube-system
spec:
  chartName: oci://registry-1.docker.io/sanselmechart/k8s-monitoring
  namespace: observability
  releaseName: k8s-monitoring
  timeout: 0s
  version: 1.6.11
  values: |
    cluster:
      name: kubernetes
    externalServices:
      prometheus:
        host: ""
        basicAuth:
          username: ""
          password: ""
        secret:
          create: true
      loki:
        host: ""
        basicAuth:
          username: ""
          password: ""
        secret:
          create: true
      tempo:
        host: ""
        basicAuth:
          username: ""
          password: ""
        secret:
          create: true
      pyroscope:
        host: ""
        basicAuth:
          username: ""
          password: ""
        secret:
          create: true
    metrics:
      enabled: false
      alloy:
        enabled: true
      kube-state-metrics:
        enabled: true
      node-exporter:
        enabled: true
      kubelet:
        enabled: true
      kubeletResource:
        enabled: true
      cadvisor:
        enabled: true
      apiserver:
        enabled: true
      kubeControllerManager:
        enabled: true
      kubeProxy:
        enabled: true
      kubeScheduler:
        enabled: true
      cost:
        enabled: true
      kepler:
        enabled: true
      beyla:
        enabled: true
      podMonitors:
        enabled: true
      probes:
        enabled: true
      serviceMonitors:
        enabled: true
      kubernetesMonitoring:
        enabled: true
    logs:
      enabled: false
      pod_logs:
        enabled: false
      podLogsObjects:
        enabled: false
      cluster_events:
        enabled: false
      journal:
        enabled: false
    traces:
      enabled: false
    profiles:
      enabled: false
      ebpf:
        enabled: true
      java:
        enabled: true
      pprof:
        enabled: true
    configAnalysis:
      enabled: true
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    opencost:
      enabled: false
    kepler:
      enabled: false
    beyla:
      enabled: false
    alloy:
      enabled: true
