---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: sre
---
apiVersion: v1
kind: Namespace
metadata:
  name: ucp
