---
apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: k0s-addon-chart-trust-manager
  namespace: kube-system
spec:
  chartName: oci://registry-1.docker.io/sanselmechart/trust-manager
  namespace: cert-manager
  releaseName: trust-manager
  timeout: 0s
  version: v0.13.0
