---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
spec:
  test:
    enable: true
  values:
    # k8sServiceHost: 127.0.0.1
    # k8sServicePort: 6443
    operator:
      replicas: 1
    # ipam:
    #   mode: kubernetes
    gatewayAPI:
      hostNetwork:
        enabled: true
