---
# Namespace for the resources defined in this kustomization
namespace: kcm-system

# Metadata to include in the generated resources
buildMetadata:
  - managedByLabel  # Adds a label indicating the manager of the resource
  - originAnnotations  # Adds annotations indicating the origin of the resource

# Common labels to apply to all resources
commonLabels:
  k0rdent.mirantis.com/managed: "true"  # Indicates the resource is managed by Mirantis

# Options for the generator
# Disables the addition of a hash suffix to resource names
# This ensures predictable resource names
generatorOptions:
  disableNameSuffixHash: true

# List of resources to include in this kustomization
resources:
  - crd.yaml  # Configuration for CRD services
  - cni.yaml  # Configuration for CNI services
  - csi.yaml  # Configuration for CSI services
  - cm.yaml  # Configuration for Cert-Manager services
