---
kind: Component
buildMetadata:
  - managedByLabel
  - originAnnotations
generatorOptions:
  disableNameSuffixHash: true
  labels:
    component: cruiser
components:
  - knative
  # - cloud
  # - cloudvisor
