---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 10m
  releaseName: grafana
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: 8.10.3
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - # docker.io/bats/bats:1.11.1
            name: docker.io/bats/bats
            digest: sha256:e56e7c49087cb766b1ba9c5732b8f5402d289252d52f64e1eefb88269f74125c
          - # docker.io/curlimages/curl:8.12.1
            name: docker.io/curlimages/curl
            digest: sha256:94e9e444bcba979c2ea12e27ae39bee4cd10bc7041a472c4727a558e213744e6
          - # docker.io/grafana/grafana:11.5.2
            name: docker.io/grafana/grafana
            digest: sha256:8b37a2f028f164ce7b9889e1765b9d6ee23fec80f871d156fbf436d6198d32b7
          - # docker.io/grafana/grafana-image-renderer:3.12.3
            name: docker.io/grafana/grafana-image-renderer
            digest: sha256:474c9ccb781cebacd117d8b77913259a42286361133a11fa54d5e62d85bacc44
          - # docker.io/kiwigrid/k8s-sidecar:1.30.2
            name: docker.io/kiwigrid/k8s-sidecar
            digest: sha256:cdb361e67b1b5c4945b6e943fbf5909badaaeb51595eaf75fb7493b3abbbe10f
          - # docker.io/library/busybox:1.37.0
            name: docker.io/library/busybox
            digest: sha256:498a000f370d8c37927118ed80afe8adc38d1edcbfc071627d17b25c88efcab0
  values:
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true
    admin:
      # trunk-ignore(checkov/CKV_SECRET_6)
      existingSecret: grafana-creds
      userKey: username
      passwordKey: password
    plugins:
      - grafana-exploretraces-app
      - grafana-github-datasource
      - grafana-llm-app
      - grafana-lokiexplore-app
      - grafana-metricsdrilldown-app
      - grafana-oncall-app
      - grafana-pyroscope-app
      - grafana-resourcesexporter-app
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
