---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: operators
spec:
  interval: 10m
  releaseName: knative-operator
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/knative-operator
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images: []
  values: {}
