---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maas
spec:
  interval: 10m
  releaseName: maas
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/maas
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images:
          - name: docker.io/library/postgres
            newTag: 14.5
          - name: quay.io/airshipit/kubernetes-entrypoint
            newTag: latest-ubuntu_jammy
  values:
    dependencies:
      static:
        rack_controller:
          services:
            - service: maas_region
              endpoint: internal
          jobs:
            - maas-export-api-key
        region_controller:
          jobs:
            - maas-db-sync
          services:
            - service: maas_db
              endpoint: internal
        db_init:
          services:
            - service: maas_db
              endpoint: internal
        db_sync:
          jobs:
            - maas-db-init
        bootstrap_admin_user:
          jobs:
            - maas-db-sync
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
        import_resources:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
        export_api_key:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
    manifests:
      configmap_ingress: false
      maas_ingress: false
    network:
      region_api:
        ingress:
          classes:
            namespace: nginx
            cluster: nginx
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      region_proxy:
        node_port:
          enabled: false
    storage:
      syslog:
        pvc:
          class_name: standard
      rackd:
        pvc:
          class_name: standard
    conf:
      cache:
        enabled: true
      cloudconfig:
        override: true
        sections:
          bootcmd:
            - rm -fr /var/lib/apt/lists
            - sysctl net.ipv6.conf.all.disable_ipv6=1
            - sysctl net.ipv6.conf.default.disable_ipv6=1
            - sysctl net.ipv6.conf.lo.disable_ipv6=0
      maas:
        cgroups:
          disable_cgroups_region: false
          disable_cgroups_rack: false
        tls:
          enabled: true
          create: true
          insecure: "'true'"
        proxy:
          peer_proxy_enabled: false
          proxy_enabled: false
        images:
          default_os: ubuntu
          default_image: jammy
          default_kernel: ga-22.04
        credentials:
          secret:
            namespace: ucp
        syslog:
          log_level: DEBUG
        extra_settings:
          active_discovery_interval: 0
          enlist_commissioning: false
          force_v1_network_yaml: true
          network_discovery: disabled
        system_passwd: null
        system_user: null
        dns:
          require_dnssec: "no"
    pod:
      replicas:
        rack: 1
        region: 1
        syslog: 1
    endpoints:
      maas_region:
        host_fqdn_override:
          default: null
          public:
            host: maas-region.kubernetes.internal
        hosts:
          default: maas-region
        name: maas-region
        path:
          default: /MAAS
        port:
          region_api:
            internal: 80
            secure: 443
            public: 443
        scheme:
          default: https
      maas_syslog:
        host_fqdn_override:
          public:
            host: maas-syslog.kubernetes.internal
    cert_manager:
      enabled: true
      issuer:
        kind: ClusterIssuer
        name: ca-issuer
