---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tm
spec:
  interval: 10m
  releaseName: tm
  timeout: 5m
  chart:
    spec:
      chart: labsonline/charts/trust-manager
      version:
      sourceRef:
        kind: HelmRepository
        name: github
      interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  test:
    enable: true
  postRenderers:
    - kustomize:
        images: []
  values: {}
